ALTER TABLE public.report
  ADD COLUMN unauth_email varchar,
  ADD COLUMN done boolean DEFAULT false;

CREATE TABLE report_comment (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id uuid REFERENCES public.report(id),
  user_id uuid REFERENCES public.users(id),
  comment varchar,
  date_added timestamptz
);
