CREATE TYPE "barangay" AS ENUM (
  'Brgy. 1', 'Brgy. 2', 'Brgy. 3',
  'Brgy. 4', 'Brgy. 5', 'Brgy. 6',
  'Brgy. 7', 'Brgy. 8', 'Brgy. 9',
  'Brgy. 10', 'Brgy. 11',
  'Barra', 'Bocohan', 'Cotta',
  'Gulang-Gulang', 'Dalahican', 'Domoit',
  'Ibabang Dupay', 'Ibabang Iyam', 'Ibabang Talim',
  'Ilayang Dupay', 'Ilayang Iyam', 'Ilayang Talim',
  'Isabang', 'Marketview', 'Mayao Castillo',
  'Mayao Crossing', 'Mayao Kanluran', 'Mayao Parada',
  'Mayao Silangan', 'Ransohan', 'Salinas',
  'Talao-Talao'
);

CREATE TABLE barangay_information (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name barangay,
  population int,
  year int
);
