CREATE TABLE "discussion" (
  id uuid PRIMARY KEY,
  user_id uuid REFERENCES public.users(id),
  title varchar NOT NULL,
  content text NOT NULL,
  data_source jsonb NOT NULL,
  type varchar NOT NULL,
  reference_id int NOT NULL,
  date_added timestamptz
);

CREATE TABLE "discussion_comments" (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discussion_id uuid REFERENCES public.discussion(id),
  user_id uuid REFERENCES public.users(id),
  comment varchar,
  reply int REFERENCES public.discussion_comments(id),
  date_added timestamptz
);

CREATE TABLE "local_budget" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data jsonb NOT NULL,
  department varchar,
  year integer NOT NULL,
  data_source jsonb NOT NULL
);

CREATE TABLE "procurement" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source varchar NOT NULL,
  pricebid int NOT NULL,
  date timestamptz,
  data_source jsonb NOT NULL
);


